### ISSUE TITLE
Dashboard bug: Server does not show

### ISSUE THREAD

**Issue by pokeacer** [iDroid27210/ibot#158]
When trying to invite iBot to the server `foxverse`, the server did not show up in my server list. I had Manage Server permissions, and yet nothing. Artuto had to give me an OAuth2 link:

Suggestion: Give a link but explain that it should only be used for backup

**Comment by iDroid27210** [comment]
I'll stop using that system anyway (kinda annoying indeed). I'll just keep the redirect after adding to the server page.
Thanks anyway :ok_hand:
