### ISSUE TITLE
Hardcoded server URLs.

### ISSUE THREAD

**Issue by MikeModder** [iDroid27210/ibot#160]
Some places use a hardcoded URL for API calls. (`https://ibot.idroid.me`). I think that, instead of hardcoding the URLs, they could be stored in the config file? You already use the configuration file to store what port to listen on, so I think this would be a good addition.

One such hardcoded URL is line 326 in server.ejs `updateRequest.open('POST', 'https://ibot.idroid.me/api/guild/modAction', true);`

**Comment by iDroid27210** [comment]
Indeed, I'm actually doing that for the rewrite ^_^
I'll keep hardcoded URLs for that version, unless smth force me to change them.
Anyway the dashboard is dead for now (problem with the VPS) so..

**Comment by MikeModder** [comment]
Ah I see. Good luck with the rewrite and such!
