### ISSUE TITLE
Duplicates Bot Messages

### ISSUE THREAD

**Issue by CleverSource** [iDroid27210/ibot#162]
The bot keeps duplicating messages.

**Comment by iDroid27210** [comment]
The bot isn't messed up for me :eyes:
Where is the bot doing that ? (guild ID)

**Comment by CleverSource** [comment]
It was on my testing guild I kicked the bot cause it was being fat for me.
Guild ID: 380816328082063372
Invite: https://discord.gg/aA8HMH6

**Comment by iDroid27210** [comment]
Problem fixed :ok_hand:
