### ISSUE TITLE
[IDEA] Add the caller to the hang-up message

### ISSUE THREAD

**Issue by MikeModder** [iDroid27210/ibot#167]
In a server I'm in, we are constantly missing calls and we have no idea who's calling, so we can never return the call. Perhaps add the caller to the hang-up message, or add an option to log incoming (and possibly outgoing) calls in the server log?

Nothing important, just something I thought would be nice to have.

**Comment by iDroid27210** [comment]
It annoys me so... let's do that ecks dee

**Comment by iDroid27210** [comment]
Done 👌
