### ISSUE TITLE
Hackban error says "You can't kick yourself"

### ISSUE THREAD

**Issue by MikeModder** [iDroid27210/ibot#168]
Line 8 in hackban.js is `if (ctx.member.id === id) return ctx.channel.send(client.I18n.translate`❌ You cannot kick yourself!`);` which references kick despite this clearly being hackban. Not sure if this was a copy-paste error, or an error at all but I figured I'd point it out.

**Comment by MikeModder** [comment]
bump

**Comment by iDroid27210** [comment]
lol indded, I fix that asap
Thanks !

**Comment by MikeModder** [comment]
This was fixed with PR #170 being merged (commit 7e9a2c2) so I'll close this.
