### ISSUE TITLE
Aliases for 'choose' (and possibly other commands) don't show up.

### ISSUE THREAD

**Issue by MikeModder** [iDroid27210/ibot#2]
Typing `i:help choose` gives help for the command, but it's alias isn't shown. `i:select` works properly, but isn't properly listed as a alias.

Edit: Screenshot https://vgy.me/juAdac.jpg

**Comment by iDroid27210** [comment]
Fixed in commit [0a8def7](https://github.com/iDroid27210/ibot/commit/0a8def7e65b49e1fb3e40034552c2dded77e1708)

Thanks for the bug report
